# GitHub Sponsors Configuration
# This adds a "❤️ Sponsor" button to your repository

# Ko-fi (Your donation platform)
ko_fi: patrickkofi
# Uncomment and add your username if you use any of these platforms:
# github: [yourusername]
# patreon: yourusername
# custom: ['https://www.buymeacoffee.com/yourusername']
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: yourusername
# issuehunt: yourusername
# open_collective: project-name
